# Generated by Django 4.2.6 on 2023-11-01 10:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBodyInput',
            fields=[
                ('height', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('gender', models.CharField(choices=[('male', '남성'), ('female', '여성')], max_length=6)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
