# Generated by Django 4.2.6 on 2023-11-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbodyinput',
            name='height',
        ),
        migrations.RemoveField(
            model_name='userbodyinput',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userbodyinput',
            name='weight',
        ),
        migrations.AlterField(
            model_name='userbodyinput',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
