# Generated by Django 4.2.6 on 2023-11-01 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_userbodyinput_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbodyinput',
            name='height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userbodyinput',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userbodyinput',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
