# Generated by Django 4.2.6 on 2023-11-01 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0004_userbodyinput_height_userbodyinput_weight_and_more'),
    ]


    operations = [
        migrations.CreateModel(
            name='UserCompareInput',
            fields=[

                ('top', models.CharField(choices=[('big', '크다'), ('soso', '보통'), ('samll', '작다')], max_length=6)),
                ('bottom', models.CharField(choices=[('big', '크다'), ('soso', '보통'), ('samll', '작다')], max_length=6)),
                ('chest', models.CharField(choices=[('big', '크다'), ('soso', '보통'), ('samll', '작다')], max_length=6)),
                ('shoulder', models.CharField(choices=[('big', '크다'), ('soso', '보통'), ('samll', '작다')], max_length=6)),
                ('arm', models.CharField(choices=[('big', '크다'), ('soso', '보통'), ('samll', '작다')], max_length=6)),
                ('neck', models.CharField(choices=[('big', '크다'), ('soso', '보통'), ('samll', '작다')], max_length=6)),
                ('waist', models.CharField(choices=[('big', '크다'), ('soso', '보통'), ('samll', '작다')], max_length=6)),
                ('ass', models.CharField(choices=[('big', '크다'), ('soso', '보통'), ('samll', '작다')], max_length=6)),
                ('thighs', models.CharField(choices=[('big', '크다'), ('soso', '보통'), ('samll', '작다')], max_length=6)),



                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
