# Generated by Django 4.2.6 on 2023-11-13 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0005_usercompareinput_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompareinput',
            name='arm',
            field=models.CharField(choices=[('big', '크다'), ('soso', '보통'), ('small', '작다')], max_length=6),
        ),
        migrations.AlterField(
            model_name='usercompareinput',
            name='ass',
            field=models.CharField(choices=[('big', '크다'), ('soso', '보통'), ('small', '작다')], max_length=6),
        ),
        migrations.AlterField(
            model_name='usercompareinput',
            name='bottom',
            field=models.CharField(choices=[('big', '크다'), ('soso', '보통'), ('small', '작다')], max_length=6),
        ),
        migrations.AlterField(
            model_name='usercompareinput',
            name='chest',
            field=models.CharField(choices=[('big', '크다'), ('soso', '보통'), ('small', '작다')], max_length=6),
        ),
        migrations.AlterField(
            model_name='usercompareinput',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usercompareinput',
            name='neck',
            field=models.CharField(choices=[('big', '크다'), ('soso', '보통'), ('small', '작다')], max_length=6),
        ),
        migrations.AlterField(
            model_name='usercompareinput',
            name='shoulder',
            field=models.CharField(choices=[('big', '크다'), ('soso', '보통'), ('small', '작다')], max_length=6),
        ),
        migrations.AlterField(
            model_name='usercompareinput',
            name='thighs',
            field=models.CharField(choices=[('big', '크다'), ('soso', '보통'), ('small', '작다')], max_length=6),
        ),
        migrations.AlterField(
            model_name='usercompareinput',
            name='top',
            field=models.CharField(choices=[('big', '크다'), ('soso', '보통'), ('small', '작다')], max_length=6),
        ),
        migrations.AlterField(
            model_name='usercompareinput',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usercompareinput',
            name='waist',
            field=models.CharField(choices=[('big', '크다'), ('soso', '보통'), ('small', '작다')], max_length=6),
        ),
    ]
